name: epub_reader_app
description: A cross-platform EPUB reader with reading progress sync.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  epub_view: ^3.2.0
  flutter_html: ^3.0.0
  flutter_math_fork: ^0.7.4
  flutter_svg: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/BloodMeridian.epub
